#ifndef GARDUINO_TASK_RUN_WATERING_H
#define GARDUINO_TASK_RUN_WATERING_H

/**
 * Registers:
 *  - First     - Counts pulses generated by flowmeter. Do not fill manually.
 *  - Second    - Is valve already opened or not? Do not fill manually!
 *  - Third     - Last number of liters that was printed to display (in manual mode only). Only when
 *                value stored in this register differs from the one calculated from pulses in First
 *                register, displayed value is re-rendered.
 * 
 * States:
 *  - WateringAutomatic - Start watering and then return to sleep mode
 *  - ManualWatering    - Start watering and return to main menu.
*/
void TaskRunWatering();

#endif