#ifndef CONFIG_HPP
#define CONFIG_HPP

#include <Arduino.h>
#include "Display/SSD1306Ascii.h"

const bool DEBUG = true;

///////////////////////////////////////////////////////////////////////////////
// JOYSTICK
///////////////////////////////////////////////////////////////////////////////

/// Update interval in ms for joystick
#define JOYSTICK_UPDATE_INTERVAL 250

/// Analog pin for reading X axis of connected joystick
#define JOYSTICK_PIN_X_AXIS A0

/// Analog pin for reading Y axis of connected joystick
#define JOYSTICK_PIN_Y_AXIS A1

/// Digital pin for reading push button status
#define JOYSTICK_PIN_BUTTON 3

///////////////////////////////////////////////////////////////////////////////
// EEPROM
///////////////////////////////////////////////////////////////////////////////

/// Number of bytes from EEPROM start to Storage header. This points to first
/// address dedicated for Storage.
#define STORAGE_OFFSET_IN_BYTES 0

/// Number of bytes in available for Storage. Don't forget to count offset in!
#define STORAGE_SIZE_IN_BYTES 1023 // 1024 (total size) - 0 (offset) - 1 (header)

/// Number of varibales stored in EEPROM
#define STORAGE_VARIABLES_COUNT 5

/// Indexes of all variables stored in EEPROM. Those are used for
/// reading and writing variables to and from memory.
#define HUMIDITY_THRESHOLD_INDEX 0
#define LITERS_PER_WATERING_INDEX 1
#define HUMIDITY_CHECK_INTERVAL_INDEX 2
#define LITERS_TOTAL_INDEX 3
#define LAST_HUMIDITY_INDEX 4   ///< Humidity value of last measurement

///////////////////////////////////////////////////////////////////////////////
// DISPLAY
///////////////////////////////////////////////////////////////////////////////

// Display address for I2C connection
#define DISPLAY_I2C_ADDRESS 0x3C
#define DISPLAY_TYPE &Adafruit128x32
#define DISPLAY_FONT System5x7
#define DISPLAY_NUM_LINES 3
#define DISPLAY_NUM_CHARACTERS 25

#define MENU_HEADER_LENGTH 15

///////////////////////////////////////////////////////////////////////////////
// EVENTS
///////////////////////////////////////////////////////////////////////////////

#define EVENTS_POOL_SIZE 10

///////////////////////////////////////////////////////////////////////////////
// APPLICATION
///////////////////////////////////////////////////////////////////////////////

/// Number of app screens. Value is used for generating list of all app screens.
#define APP_SCREENS_COUNT 3

///////////////////////////////////////////////////////////////////////////////
// INTERRUPTIONS
///////////////////////////////////////////////////////////////////////////////

/// Pin connected to flowmeter. When watering is running, this pin is used
/// to count number of liters used.
#define INTERRUPT_PIN_FLOWMETER 2

/// This pin is connected to control joystick used for manual wake up.
#define INTERRUPTION_PIN_MANUAL_WAKEUP JOYSTICK_PIN_BUTTON

/// How long should garduino be sleeping between soil humidity checks.
#define SLEEP_NUMBER_OF_SECONDS 16

/// Number of seconds between interruptions generated by watchdog. Do not change
/// this value unless you change prescaler in Interruptions.cpp as well!
#define SLEEP_SECONDS_PER_INTERRUPTION 8

///////////////////////////////////////////////////////////////////////////////
// RUNTIME
///////////////////////////////////////////////////////////////////////////////

/// Default values for all variables stored in EEPROM.
#define DEFAULT_HUMIDITY_THRESHOLD 120
#define DEFAULT_LITERS_PER_WATERING 5
#define DEFAULT_HUMIDITY_CHECK_INTERVAL 30
#define DEFAULT_LITERS_TOTAL 0
#define DEFAULT_LAST_HUMIDITY 0

// TODO: Change pin to something real :)
#define HUMIDITY_PIN_READ 5

/// Number of pulses generated per one liter by flowmeter.
#define FLOWMETER_PULSES_PER_LITER 450

#endif 