#ifndef INTERRUPTIONS_HPP
#define INTERRUPTIONS_HPP

#include "./Events/Event.hpp"
#include "garduino.hpp"
#include "config.hpp"

/**
 * This function handles pulses generated by water meter. Each second, 4.5
 * pulses are used to indicated water flow of 1l/min. 
 */
void onWaterMeterPulse() {
    Event ev;
    ev.type = EventType::WaterMeter;

    garduino.addEvent(ev);
}

#endif